### ISSUE TITLE
Shush not work

### ISSUE THREAD

**Issue by valour01** [BUseclab/hush#1]
I cloned your repo and installed it with the command 'mvn install' and 'mvn assembly:assembly'. A kindly reminder is that the file 'report.sh' in your 'distribution.xml' does not exist. I create this file and it seems work.

Then I make a directory named 'apk' under 'path/hush/shush' and put a sample apk in the directory 'path/hush/shush/apk/'. I create another directory named 'output' under 'path/hush/shush'. 

I run your script with the command './run.sh apk/sample.apk output/ SourcesAndSinks_1.txt'. However, many error logs were created inside the directory 'path/hush/shush' and many directories whose names were not readable(seems like binary)  are created in the directory 'path/hush/shush/output'.

I don't know what's going wrong and I hope to get your help. If you need more information to locate the problem, please tell me. Many thanks

**Comment by wil3** [comment]
One thing I immediately notice is that it looks like you are trying to pass run.sh an APK rather than a text file containing the paths to the APKs. When running large batches of files this is very helpful. If you want to run individual APKs look at how the Java class is called in https://github.com/BUseclab/hush/blob/master/shush/run.sh. I updated https://github.com/BUseclab/hush/tree/master/shush with additional details. For any further issues please submit an issue for each one (ie a distribution issue and run.sh issue) and also include all logs. Thanks!
